In [1]:
import open3d as o3d
import numpy as np
import matplotlib.pyplot as plt

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [14]:

print("->正在加载点云... ")
pcd = o3d.io.read_point_cloud("training_50_classes\Lille2.ply",format= 'ply')
o3d.visualization.draw_geometries([pcd])

->正在加载点云... 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 句柄无效。 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 句柄无效。 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 不支持请求的转换操作。 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 不支持请求的转换操作。 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 句柄无效。 


In [3]:
# pcd.colors[[2200,2500], : ] = [0, 0, 1]
print(np.asarray(pcd.points))

[[-673.73962402 -625.83459473   42.38851547]
 [-673.82873535 -625.73248291   42.40692139]
 [-671.86029053 -622.27850342   36.9738884 ]
 ...
 [-769.46075439 -715.39654541   28.40760231]
 [-769.67773438 -715.75396729   28.40439224]
 [-769.5355835  -716.04003906   28.40219116]]


In [4]:
print("->正在RANSAC平面分割...")
distance_threshold = 0.2    # 内点到平面模型的最大距离
ransac_n = 3                # 用于拟合平面的采样点数
num_iterations = 1000       # 最大迭代次数

# 返回模型系数plane_model和内点索引inliers，并赋值
plane_model, inliers = pcd.segment_plane(distance_threshold, ransac_n, num_iterations)

# 输出平面方程
[a, b, c, d] = plane_model
print(f"Plane equation: {a:.2f}x + {  b:.2f}y + {  c:.2f}z + {  d:.2f} = 0")

# 平面内点点云
inlier_cloud = pcd.select_by_index(inliers)
inlier_cloud.paint_uniform_color([0, 0, 1.0])
print(inlier_cloud)

# 平面外点点云
outlier_cloud = pcd.select_by_index(inliers, invert=True)
outlier_cloud.paint_uniform_color([1.0, 0, 0])
print(outlier_cloud)

# 可视化平面分割结果
o3d.visualization.draw_geometries([inlier_cloud,outlier_cloud])

->正在RANSAC平面分割...
Plane equation: -0.02x + -0.01y + 1.00z + -56.93 = 0
PointCloud with 6116612 points.
PointCloud with 3462161 points.
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 句柄无效。 


In [7]:
# 可视化平面分割结果
o3d.visualization.draw_geometries([inlier_cloud])

[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 句柄无效。 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 不支持请求的转换操作。 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 不支持请求的转换操作。 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 不支持请求的转换操作。 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 句柄无效。 
